In [68]:
import numpy as np
import torch

In [69]:
lista = [
    [1,2,3],
    [4,5,6]
]

# O tipo padrao e um tensor float 32 bits
tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [70]:
# Outros tipos
# double (float 64 bits)
tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

# Conversao explicita para 32 bits
tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

# Int
tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [71]:
# Outras formas de inicializar tensores
# O tipo do tensor e o tipo do array sao os mesmos
# A partir de arrays NumPy
arr = np.random.rand(3, 4) # array aleatorio de 3 linhas e 4 colunas
tns = torch.from_numpy(arr)
print(arr)
print(tns)

arr = np.random.rand(3, 4) # array aleatorio de 3 linhas e 4 colunas
arr = arr.astype(int)
tns = torch.from_numpy(arr)
print(arr)
print(tns)

[[0.87896311 0.93771195 0.69532997 0.38514718]
 [0.8014956  0.79388584 0.06300936 0.49063281]
 [0.67227035 0.81287404 0.13490315 0.25370977]]
tensor([[0.8790, 0.9377, 0.6953, 0.3851],
        [0.8015, 0.7939, 0.0630, 0.4906],
        [0.6723, 0.8129, 0.1349, 0.2537]], dtype=torch.float64)
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [72]:
# Tensores inicializados
tns1 = torch.ones(2, 3)
tns0 = torch.zeros(4, 5)
tnsr = torch.randn(3, 3) # preenchimento de acordo com uma distribuicao normal

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[-1.1777,  1.3018, -0.5093],
        [ 1.8644,  0.8149,  0.5681],
        [-1.0523,  0.9092,  0.2295]])


In [73]:
# Tensor para array NumPy
arr = tnsr.data.numpy()
print(arr)

[[-1.1776994   1.3017564  -0.5092827 ]
 [ 1.86438     0.8149002   0.56807715]
 [-1.0522925   0.90919787  0.22948852]]


In [74]:
# Tipo tensor
print(type(tnsr))
arr = tnsr.data.numpy()
print(type(arr))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [75]:
# Indexacao (acessar partes do tensor)
# Sintaxe similar a NumPy usando colchetes []
print(tnsr)
tnsr[0, 2] = -10

print('')
print(tnsr)

print('')
print(tnsr[0:2]) # acessa linhas 0 e 1, mas nao 2. Elemento a direita de : nao eh incluido

print('')
print(tnsr[:, 2]) # todas as linhas da coluna 2

print('')
print(tnsr[0,2]) # um unico elemento
print(tnsr[0,2].size()) # size() nao retorna nada. Tensor de 0 dimensoes


tensor([[-1.1777,  1.3018, -0.5093],
        [ 1.8644,  0.8149,  0.5681],
        [-1.0523,  0.9092,  0.2295]])

tensor([[ -1.1777,   1.3018, -10.0000],
        [  1.8644,   0.8149,   0.5681],
        [ -1.0523,   0.9092,   0.2295]])

tensor([[ -1.1777,   1.3018, -10.0000],
        [  1.8644,   0.8149,   0.5681]])

tensor([-10.0000,   0.5681,   0.2295])

tensor(-10.)
torch.Size([])


In [76]:
# Operacoes
# Sao realizadas ponto a ponto, ou seja, (i, j) o numero de dimensoes deve ser o mesmo
print(tnsr.shape)
print(tns1.shape)

tns = tnsr[0:2, :]
print('')
print(tns.shape)
print(tns1.shape)

print('')
print(tns + tns1)
print(tns - tns1)
print(tns + tns1)
print(tns * tns1) # esta nao eh a multiplicacao de matriz que conhecemos! Ha uma funcao especifica para isso
print('')
print(torch.mm(tns,tns1.T)) # produto interno. como as matrizes possuem ambas dimensao 2x3, foi necessario fazer a transposta de uma delas, ficando 2x3 e 3x2
# tns1 -> (n x m)
# tns2 -> (m x p)
# resultado -> (m x p)

torch.Size([3, 3])
torch.Size([2, 3])

torch.Size([2, 3])
torch.Size([2, 3])

tensor([[-0.1777,  2.3018, -9.0000],
        [ 2.8644,  1.8149,  1.5681]])
tensor([[ -2.1777,   0.3018, -11.0000],
        [  0.8644,  -0.1851,  -0.4319]])
tensor([[-0.1777,  2.3018, -9.0000],
        [ 2.8644,  1.8149,  1.5681]])
tensor([[ -1.1777,   1.3018, -10.0000],
        [  1.8644,   0.8149,   0.5681]])

tensor([[-9.8759, -9.8759],
        [ 3.2474,  3.2474]])


In [77]:
# Extrema importancia redimensionar tensores, para torna-los lineares
tns = torch.randn(2,2,3)
print(tns)

print(tns.size())

# Muito comum
tns = tns.view(tns.size(0), -1) # mantem a primeira dimensao e achata o resto. -1 achata o tensor
print(tns)

tensor([[[-1.6920,  0.4096,  1.8580],
         [ 1.6554,  1.2220, -0.0231]],

        [[-1.0955,  0.0280,  0.5204],
         [ 0.5908,  0.4295, -0.3835]]])
torch.Size([2, 2, 3])
tensor([[-1.6920,  0.4096,  1.8580,  1.6554,  1.2220, -0.0231],
        [-1.0955,  0.0280,  0.5204,  0.5908,  0.4295, -0.3835]])


In [78]:
# Eh possivel usar GPU
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
print(device)

tns = tns.to(device)
print(tns)

cpu
tensor([[-1.6920,  0.4096,  1.8580,  1.6554,  1.2220, -0.0231],
        [-1.0955,  0.0280,  0.5204,  0.5908,  0.4295, -0.3835]])


In [79]:
# Atividade
# crie um tensor aleatório tns1 com a dimensionalidade 7 x 7 x 3 e um outro tensor aleatório tns2 de 147 x 1. Modificando apenas tns1 some os dois tensores
tns1 = torch.randn(7,7,3)
tns2 = torch.randn(147,1)

tns1 = tns1.view(-1,1) # 7 * 7 * 3 = 147. Achata tns1 e fixa a outra dimensao em 1
print(tns1 + tns2)

tensor([[ 3.6453e-01],
        [ 1.3582e+00],
        [ 4.5206e-01],
        [ 2.6517e+00],
        [-3.5180e-01],
        [ 1.5601e+00],
        [ 2.6650e+00],
        [-8.0895e-01],
        [ 2.6918e+00],
        [-3.1644e-01],
        [ 4.6013e-01],
        [-1.1671e+00],
        [ 2.9454e+00],
        [-1.2373e+00],
        [ 1.3789e+00],
        [-3.7777e-01],
        [ 9.5224e-02],
        [-3.4927e-01],
        [-1.1112e+00],
        [-5.4400e+00],
        [ 6.4987e-01],
        [-5.5091e-01],
        [ 1.4023e+00],
        [-2.3615e+00],
        [-3.8897e-01],
        [-9.0246e-02],
        [ 9.6226e-01],
        [-1.3765e+00],
        [ 2.3905e-01],
        [ 1.0774e+00],
        [ 2.4540e+00],
        [ 1.6077e+00],
        [ 1.9475e+00],
        [ 2.1612e+00],
        [ 1.5775e+00],
        [-1.2572e+00],
        [-3.2748e-01],
        [-1.4875e+00],
        [ 3.4122e+00],
        [ 4.2981e-01],
        [ 1.2273e+00],
        [-1.1511e+00],
        [-2.3400e+00],
        [-3